modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId="basicmod" #mandatory
version="${version}" #mandatory
displayName="Basic Mod" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
