modLoader="javafml"

loaderVersion="[30,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="banana" #mandatory

version="1.0" #mandatory

displayName="Mod Tutorial Mod" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Love, Cheese and small house plants" #optional

description='''
    Howdy, this is a simple description in long-form.
'''


[[dependencies.banana]]
modId="forge"
mandatory=true
versionRange="[30,)"
ordering="NONE"
side="BOTH"